### ISSUE TITLE
OpenShift token has expired

### ISSUE THREAD

**Issue by pmonks** [symphonyoss/bot-unfurl#64]
### Steps to Reproduce:
 1. Trigger a Travis CI build (e.g. make a commit)

### Expected Result:
The JDK8 job on Travis CI deploys the updated JARs to OpenShift, running against the `foundation-dev` pod.

### Actual Result:
The [JDK8 job fails](https://travis-ci.org/symphonyoss/bot-unfurl/jobs/421263807#L826) with the message: `error: The token provided is invalid or expired.`

**Comment by pmonks** [comment]
@maoo any updates on this?  This [issue is still occurring](https://travis-ci.org/symphonyoss/bot-unfurl/jobs/428792188#L826).

**Comment by maoo** [comment]
I've added an `OC_TOKEN` variable via Travis (encrypted) settings; could you please remove [it from travis.yml](https://github.com/symphonyoss/bot-unfurl/blob/master/.travis.yml#L11-L12) and restart [the last Travis job](https://travis-ci.org/symphonyoss/bot-unfurl/jobs/428792188)?

**Comment by pmonks** [comment]
@maoo Can you please update the `.travis.yml` file with the new encrypted `OC_TOKEN` value instead?  It's better practice to store and manage CI settings in the git repository itself (i.e. in the `.travis.yml` file), rather than as "magic" settings buried in the Travis UI that some of the project's developers may not have access to.

The steps to do this (assuming you have the [Travis CI command line tools](https://github.com/travis-ci/travis.rb#readme) installed) are: 

1. `git clone https://github.com/symphonyoss/bot-unfurl.git`
2. `git checkout dev`
3. `travis encrypt OC_TOKEN=<new value of token>`
4. Copy the `secure=...` line from the console
5. Open `.travis.yml` in a text editor
6. Navigate to [line 12](https://github.com/symphonyoss/bot-unfurl/blob/dev/.travis.yml#L12)
7. Replace the value with the text from the clipboard, **ensuring the indent, up to and including the hyphen (-) character, at the start of the line is preserved**
8. Save and exit
9. `git commit -m ':arrow_up: Update expired OC_TOKEN for OpenShift deployment' .travis.yml`
10. `git push`

**Comment by maoo** [comment]
All done

**Comment by pmonks** [comment]
@maoo careful with the @finos-admin account - it shouldn't be used for git-level changes to projects.  😉
