### ISSUE TITLE
Upgrade OpenShift runtime to use latest Java LTS version (11)

### ISSUE THREAD

**Issue by pmonks** [symphonyoss/bot-unfurl#65]
See https://github.com/finos-fdx/bot-github-chatops/issues/51.  This is really just one task, but affects both projects equally so I'm capturing it in both places.

**Comment by pmonks** [comment]
@maoo any updates on this?  JDK 1.8 is getting quite long in the tooth now.

**Comment by pmonks** [comment]
@maoo am I right in thinking this is now fixed?

**Comment by maoo** [comment]
Yes, thanks!
