### ISSUE TITLE
Logging configuration for Openshift deploment

### ISSUE THREAD

**Issue by maoo** [symphonyoss/bot-unfurl#7]
Currently the bot-unfurl instance deployed on Openshift uses a log4j `DEBUG` level, which is extremely verbose; additionally, log4j fails at startup with a `FileNotFoundException` on `../logs/SymphonyClient.log`, see https://gist.github.com/maoo/cd07f55cd98f35b5ea252a44e83a1b43

The command executed by container to start the bot is `java -cp /opt/openshift/bot-unfurl-standalone.jar bot_unfurl.main -c /opt/openshift/etc/config.edn`; we could add  a `-Dlog4j.configuration` and point it to a file that is shipped into `./uberjar/etc` folder.

The file could be copied by `./build-uberjar.sh` script.

**Comment by maoo** [comment]
Submitted PR - https://github.com/symphonyoss/bot-unfurl/pull/8

**Comment by pmonks** [comment]
The [readme](https://github.com/symphonyoss/bot-unfurl/blob/master/README.md) describes how to specify a log4j configuration at runtime.
