### ISSUE TITLE
OpenShift token has expired, yet again

### ISSUE THREAD

**Issue by pmonks** [symphonyoss/bot-unfurl#70]
See the latest [TravisCI build log](https://travis-ci.org/symphonyoss/bot-unfurl/jobs/461923947#L879).

@maoo this is incredibly irritating - can you please escalate this to your RedHat OpenShift contacts again?  Thanks!

**Comment by maoo** [comment]
TY for raising this again @pmonks . I reached out to OpenShift , I'll change the keys  and keep you posted.

**Comment by maoo** [comment]
@pmonks - found the solution! OpenShift service account tokens don't expire, so they can be configured once and will work forever.

The downside is that they are too long to encrypted using `travis encrypt OC_TOKEN=...`; I've used Travis Settings to setup OC_TOKEN environment variable and works as expected.

I tested it on bot-github-chatops, check https://travis-ci.org/finos-fdx/bot-github-chatops/jobs/463216293

If you like the approach, I can setup OC_TOKEN in the Travis CI settings of bot-unfurl; you'd need to remove the secret environment from `.travis.yml` too.

**Comment by pmonks** [comment]
As you know I'm very against magical configuration settings hidden in UIs, so would instead suggest putting the key in a [Travis encrypted file](https://github.com/travis-ci/travis.rb#encrypt-file), and then adding `before_install` stage steps to the `.travis.yml` to decrypt the file and assign its content to the `OC_TOKEN` env var.

wdyt?

**Comment by maoo** [comment]
I got it working on bot-github-chatops, see https://github.com/finos-fdx/bot-github-chatops/commit/8f5a70d3a1cc1e07625735ca0e12dfc6ee7449bc 

The logic is embedded in the oc-deploy.sh script, see https://github.com/finos-fdx/contrib-toolbox/blob/master/scripts/oc-deploy.sh#L130-L132

To make it work on bot-unfurl, I'd need to use `finos-admin` credentials to push the encrypted file on this repo (`dev` branch); can I proceed?

**Comment by pmonks** [comment]
@maoo yep please do!  I'd prefer it were done under your @maoo login, if possible.  Doing things as @finos-admin messes up the Bitergia stats.  😉

**Comment by maoo** [comment]
PR sent, see https://github.com/symphonyoss/bot-unfurl/pull/72

Not sure it will work, as I created the encrypted file on a different repo, and seems that Travis CI uses the repo location to generate encryption keys.

We can try to merge to dev and see what happens? If not working, I can step in as finos-admin.

Also, https://github.com/symphonyoss/bot-unfurl/pull/71 can be closed.

**Comment by maoo** [comment]
After fighting with [travis multiple encrypted file limitations](https://docs.travis-ci.com/user/encrypting-files#Encrypting-multiple-files), we got it working.

Build is green and OpenShift deployment completed successfully. @pmonks please review and close issue if you're happy with the results.

**Comment by pmonks** [comment]
@maoo review which PR?  Did you mean to close #72 without it being merged?

**Comment by maoo** [comment]
no PR to review, just the result :-) everything is green, I guess this issue can be closed.

**Comment by pmonks** [comment]
Oh yeah - it's just a commit to `dev`. 😉   LGTM - I have some other changes to make and will then look at rolling a new release (i.e. merging to `master`).
